### PR TITLE
Render viewpoint directions

### PR DESCRIPTION
**Pull request by max-dn**
Patch for #109 

You have to install this function once after creating the database
`psql gis <  mapnik/tools/viewpointdirection.sql`
(error messages like "type otm_vp_viewrange already exists" are ok, that means someone else has installed it before)

### CODE REVIEW

**Comment by max-dn** [comment]
I appended a commit to activate attraction in opentopomap.xml. It was deactivated in #110 and I saw there is a update in progress with attractions.

**Comment by imagico** [comment]
Can't you use a subquery like

```
(SELECT way,tourism,
  int_dir.s1 as firstrotation,int_dir.a1 as firstangle,
  int_dir.s2 as secondrotation,int_dir.a2 as secondangle 
  FROM (SELECT way,tourism, viewpointdirection(direction) AS int_dir 
    FROM planet_osm_point WHERE tourism='viewpoint') AS viewpoints)
```

**Comment by max-dn** [comment]
I think this will prevent postgresql to use the spacial index (the most important index and in most cases the only index we have). Mapnik will convert this to
`SELECT way... FROM (SELECT way ... FROM ... WHERE...) WHERE way && bbox`
and so we will first search all nodes of the planet inside the brackets and then have a look which of them are in the bounding box...
But I will try a debug session with this, maybe postgresql is smart enough to optimize this.

**Comment by imagico** [comment]
I don't know but we have many nested queries of this kind in osm-carto - like:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L594

**Comment by max-dn** [comment]
You are right.

The query results in a nested select anyway:
`SELECT ST_AsBinary("way") AS geom,"firstangle","firstrotation","secondangle","secondrotation","tourism" FROM 
        (SELECT way,tourism,
                   (viewpointdirection(direction)).s1 as firstrotation,
                   (viewpointdirection(direction)).a1 as firstangle,
                   (viewpointdirection(direction)).s2 as secondrotation,
                   (viewpointdirection(direction)).a2 as secondangle FROM planet_osm_point 
               WHERE tourism='viewpoint') AS symbols 
              WHERE "way" && ST_SetSRID('BOX3D(..,.. ..,..)'::box3d, 3857)`

So if not all mapnik maps are wrong, my idea about the cleverness of postgresql is wrong..

I will try it when I have time for testing...

Thanks

**Pull request merged**
